<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="ru" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="ru" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="ru" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="ru" class="no-js"> <!--<![endif]-->
<head>
    <!-- meta character set -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Always force latest IE rendering engine or request Chrome Frame -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- Meta Description -->
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="SEV">

    <title>
        <?=$this->pageTitle?>
    </title>
    <?=$this->cssString?>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>

    <!-- Fontawesome Icon font -->
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <!-- bootstrap.min -->
    <link rel="stylesheet" href="/css/jquery.fancybox.css">
    <!-- bootstrap.min -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <!-- bootstrap.min -->
    <link rel="stylesheet" href="/css/owl.carousel.css">
    <!-- bootstrap.min -->
    <link rel="stylesheet" href="/css/slit-slider.css">
    <!-- bootstrap.min -->
    <link rel="stylesheet" href="/css/animate.css">
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="/css/main.css">

    <!-- Modernizer Script for old Browsers -->
    <script src="/js/modernizr-2.6.2.min.js"></script>

</head>

<body id="body">
<!-- preloader -->
<div id="preloader">
    <div class="loder-box">
        <div class="battery"></div>
    </div>
</div>
<!-- end preloader -->

