<?php
class Feed_Controller_GetMy extends Base_Controller
{
    public function __construct($view)
    {
        parent::__construct($view);
    }

    public function preProcess()
    {
        parent::preProcess(); // TODO: Change the autogenerated stub
        if (!$this->USER) {
            return $this->needAuthUser();
        }
        return true;
    }

    public function indexAction()
    {
        if ($_SERVER['REQUEST_METHOD'] === 'GET') {
            return $this->getMy();
        }
    }

    public function getMy()
    {
        $res = Feed_Service_Article::getMyFeed($this->USER->getId(), 10, 0);
        return $this->view->setAjax(['articles' => $res]);
    }
}