<!-- Bootstrap core JavaScript-->
<script src="/fadmin/vendor/jquery/jquery.min.js"></script>
<script src="/fadmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/fadmin/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Page level plugin JavaScript-->
<script src="/fadmin/vendor/chart.js/Chart.min.js"></script>
<script src="/fadmin/vendor/datatables/jquery.dataTables.js"></script>
<script src="/fadmin/vendor/datatables/dataTables.bootstrap4.js"></script>
<!-- Custom scripts for all pages-->
<script src="/fadmin/js/sb-admin.min.js"></script>
<!-- Custom scripts for this page-->
<script src="/fadmin/js/sb-admin-datatables.min.js"></script>
<!--<script src="/fadmin/js/sb-admin-charts.min.js"></script>-->

</body>

</html>
